# Generated by Django 5.2.5 on 2025-09-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_brand_product_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Mark as premium tile'),
        ),
    ]
